# Generated by Django 2.2.12 on 2021-12-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.CharField(choices=[('PP', 'Privacy policy'), ('TC', 'Terms and conditions'), ('AU', 'About')], max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='policysubsection',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='policysubsection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle'),
        ),
    ]
