# Generated by Django 2.2.12 on 2021-11-30 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elevators', '0001_initial'),
        ('addresses', '0001_initial'),
        ('management', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_address', to='users.Address', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_client', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_delivery', to='elevators.Delivery', verbose_name='Delivery'),
        ),
        migrations.AddField(
            model_name='order',
            name='elevator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_elevator', to='elevators.Elevator', verbose_name='Elevator'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_payment', to='elevators.Payment', verbose_name='Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_product', to='elevators.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='railway_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_railway_station', to='addresses.RailwayStation', verbose_name='Railway station'),
        ),
        migrations.AddField(
            model_name='order',
            name='requisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_requisites', to='users.Requisites', verbose_name='Requisites'),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_vehicle', to='elevators.Vehicle', verbose_name='Vehicle'),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geolocation', to='elevators.Vehicle', verbose_name='Vehicle'),
        ),
        migrations.AddField(
            model_name='elevator',
            name='cities',
            field=models.ManyToManyField(related_name='cities', to='addresses.City', verbose_name='Cities'),
        ),
        migrations.AddField(
            model_name='elevator',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='elevator',
            name='railway_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elevator', to='addresses.RailwayStation', verbose_name='Railway station'),
        ),
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='elevators.Order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='elevator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_elevator', to='elevators.Elevator', verbose_name='Elevator'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_type', to='management.DeliveryType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='elevators.Cart', verbose_name='Cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='elevator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_elevator', to='elevators.Elevator', verbose_name='Elevator'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_product', to='elevators.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administrator',
            name='elevator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevator_administrator', to='elevators.Elevator'),
        ),
        migrations.AddField(
            model_name='accountant',
            name='accountant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountant',
            name='elevator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevator_accountant', to='elevators.Elevator'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('elevator', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('elevator', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('elevator', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='geolocation',
            unique_together={('vehicle', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='delivery',
            unique_together={('elevator', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('id', 'client')},
        ),
    ]
