# Generated by Django 2.2.12 on 2021-12-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0002_auto_20211130_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Kazakh description'),
        ),
        migrations.AddField(
            model_name='elevator',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Russian description'),
        ),
        migrations.AddField(
            model_name='elevator',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/logos/', verbose_name='Logo'),
        ),
    ]
