# Generated by Django 2.2.12 on 2021-12-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0003_auto_20211202_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='wialon_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Wialon ID'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterUniqueTogether(
            name='geolocation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('elevator', 'wialon_id')},
        ),
    ]
