# Generated by Django 2.2.12 on 2021-12-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('elevators', '0004_auto_20211209_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='elevator',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('AR', 'Archived')], default='AC', max_length=2, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='title_kk',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Kazakh title'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='title_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Russian title'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('AR', 'Archived')], default='AC', max_length=2, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='set_number',
            field=models.CharField(default=1, max_length=128, verbose_name='Set number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('AR', 'Archived')], default='AC', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='delivery',
            unique_together={('elevator', 'type', 'title_ru')},
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
