# Generated by Django 2.2.12 on 2022-01-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0005_auto_20211222_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolocation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Geolocation', 'verbose_name_plural': 'Geolocations'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
