# Generated by Django 2.2.12 on 2022-01-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0006_auto_20220112_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_limit',
            field=models.PositiveIntegerField(default=1000, verbose_name='Minimum limit'),
            preserve_default=False,
        ),
    ]
