# Generated by Django 2.2.12 on 2022-02-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0007_auto_20220131_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='title_kk',
            field=models.CharField(max_length=128, unique=True, verbose_name='Kazakh title'),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='title_ru',
            field=models.CharField(max_length=128, unique=True, verbose_name='Russian title'),
        ),
    ]
