# Generated by Django 2.2.12 on 2022-02-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0009_auto_20220203_1436'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
