# Generated by Django 2.2.12 on 2022-02-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0010_auto_20220204_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.BooleanField(default=False, verbose_name='Display on landing'),
        ),
    ]
