# Generated by Django 2.2.12 on 2022-02-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0011_auto_20220204_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='number',
            field=models.CharField(default='00', max_length=2, verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(default='00-000000', max_length=9, verbose_name='Number'),
        ),
    ]
