# Generated by Django 2.2.12 on 2022-02-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0012_auto_20220215_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='number',
            field=models.CharField(default='00', max_length=2, unique=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(default='00-000000', max_length=9, unique=True, verbose_name='Number'),
        ),
    ]
