# Generated by Django 2.2.12 on 2022-02-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20211223_1118'),
        ('elevators', '0013_auto_20220217_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='requisites',
        ),
        migrations.AddField(
            model_name='order',
            name='bik',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='BIK'),
        ),
        migrations.AddField(
            model_name='order',
            name='bin',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='BIN'),
        ),
        migrations.AddField(
            model_name='order',
            name='checking_account',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Checking account'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_address', to='addresses.City', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
    ]
