# Generated by Django 2.2.12 on 2022-02-28 14:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0014_auto_20220224_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='address_kk',
            field=models.CharField(default=1, max_length=255, verbose_name='Kazakh address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elevator',
            name='address_ru',
            field=models.CharField(default=1, max_length=255, verbose_name='Russian address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elevator',
            name='bin',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='BIN'),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='checking_account',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Checking account'),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+77777777777', max_length=128, region=None, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
