# Generated by Django 2.2.12 on 2022-03-16 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0015_auto_20220228_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.PositiveIntegerField(default=0, verbose_name='Profit')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevator_profit', to='elevators.Elevator', verbose_name='Elevator')),
            ],
        ),
    ]
