# Generated by Django 2.2.12 on 2022-03-18 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0016_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_profit', to='elevators.Order', verbose_name='Order'),
            preserve_default=False,
        ),
    ]
