# Generated by Django 2.2.12 on 2022-03-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0017_profit_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='bik',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='BIK'),
        ),
    ]
