# Generated by Django 2.2.12 on 2022-05-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0018_elevator_bik'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('content', models.CharField(blank=True, max_length=255, verbose_name='Content')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historical_orders', to='elevators.Order', verbose_name='Order')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]