version: '3.7'

services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/dev:/etc/nginx/conf.d
    networks:
      - my-network

  adminjs-ui:
    build:
      context: ./frontend/kebek-admin-client
    ports:
      - "3001:3001"
    container_name: adminjs-ui
    stdin_open: true
    volumes:
      - ./frontend/kebek-admin-client:/usr/src/app/kebek-admin-client
      - /usr/src/app/kebek-admin-client/node_modules
    env_file:
      - ./frontend/kebek-admin-client/.env
    networks:
      - my-network

  kebek-suppliers-ui:
    build:
      context: ./frontend/kebek-suppliers-personal-account
    ports:
      - "3002:3002"
    container_name: kebek-suppliers-ui
    stdin_open: true
    volumes:
      - ./frontend/kebek-suppliers-personal-account:/usr/src/app/kebek-suppliers-personal-account
      - /usr/src/app/kebek-suppliers-personal-account/node_modules
    env_file:
      - ./frontend/kebek-suppliers-personal-account/.env
    networks:
      - my-network

networks:
  my-network: