# Generated by Django 2.2.12 on 2021-11-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=32, verbose_name='Russian title')),
                ('title_kk', models.CharField(max_length=32, verbose_name='Kazakh title')),
            ],
            options={
                'verbose_name': 'Delivery type',
                'verbose_name_plural': 'Delivery types',
                'ordering': ['title_ru'],
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=32, verbose_name='Russian title')),
                ('title_kk', models.CharField(max_length=32, verbose_name='Kazakh title')),
                ('natural_person', models.BooleanField(default=True, verbose_name='Available for natural person')),
                ('legal_person', models.BooleanField(default=True, verbose_name='Available for legal person')),
            ],
            options={
                'verbose_name': 'Payment type',
                'verbose_name_plural': 'Payment types',
                'ordering': ['title_ru'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=32, verbose_name='Russian title')),
                ('title_kk', models.CharField(max_length=32, verbose_name='Kazakh title')),
            ],
            options={
                'verbose_name': 'Product type',
                'verbose_name_plural': 'Product types',
                'ordering': ['title_ru'],
            },
        ),
    ]
