# Generated by Django 2.2.12 on 2022-01-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('const', models.CharField(max_length=128, unique=True, verbose_name='Constant')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Russian title')),
                ('title_kk', models.CharField(max_length=255, verbose_name='Kazakh title')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['title_ru'],
            },
        ),
    ]
