# Generated by Django 2.2.12 on 2021-12-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='bik',
            field=models.CharField(default=1, max_length=80, verbose_name='BIK'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisites',
            name='title',
            field=models.CharField(default=0, max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='images/users/', verbose_name='Profile Picture'),
        ),
    ]
