# Generated by Django 2.2.12 on 2022-03-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_auto_20220203_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='order_status',
            field=models.CharField(choices=[('AD', 'Accepted'), ('WP', 'Waiting for prepayment'), ('WS', 'Waiting for supplement'), ('BD', 'Billed'), ('PP', 'Prepayment received'), ('PD', 'Paid'), ('PA', 'Proxy added'), ('SD', 'Shipped'), ('DD', 'Delivered'), ('CD', 'Cancelled'), ('FD', 'Finished')], default='AD', max_length=2, verbose_name='Status'),
        ),
    ]
