# Generated by Django 2.2.12 on 2022-05-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0007_auto_20220317_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='in_history',
        ),
    ]