# Generated by Django 2.2.12 on 2021-11-30 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=32, verbose_name='Russian title')),
                ('title_kk', models.CharField(max_length=32, verbose_name='Kazakh title')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['title_ru'],
            },
        ),
        migrations.CreateModel(
            name='RailwayStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=32, verbose_name='Russian title')),
                ('title_kk', models.CharField(max_length=32, verbose_name='Kazakh title')),
                ('code', models.CharField(max_length=8, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Railway station',
                'verbose_name_plural': 'Railway stations',
                'ordering': ['title_ru'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=32, verbose_name='Russian title')),
                ('title_kk', models.CharField(max_length=32, verbose_name='Kazakh title')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='addresses.District', verbose_name='District')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['district', 'title_ru'],
            },
        ),
    ]
