# Generated by Django 2.2.12 on 2021-12-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='railwaystation',
            name='description_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kazakh description'),
        ),
        migrations.AddField(
            model_name='railwaystation',
            name='description_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Russian description'),
        ),
        migrations.AlterField(
            model_name='railwaystation',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='railwaystation',
            name='title_kk',
            field=models.CharField(max_length=64, verbose_name='Kazakh title'),
        ),
        migrations.AlterField(
            model_name='railwaystation',
            name='title_ru',
            field=models.CharField(max_length=64, verbose_name='Russian title'),
        ),
    ]
