export const statusList = [
  {
    name: "Создан",
    pluralName: "Создан",
    pluralNameKk: "Құрылды",
    encryptedName: "AD",
    bg: "#EDF4FE",
    color: "#2D9CDB",
  },
  {
    name: "Выставлен счет",
    pluralName: "Выставлен счет",
    encryptedName: "BD",
    pluralNameKk: "Қойылған шот",
    bg: "#F6F4FE",
    color: "#9593F2",
  },
  {
    name: "Оплачено",
    pluralName: "Оплачен",
    pluralNameKk: "Төленді",
    encryptedName: "PD",
    bg: "#D6EFE6",
    color: "#219653",
  },
  {
    name: "Отменен",
    pluralName: "Отменен",
    encryptedName: "CD",
    pluralNameKk: "Жойылған",
    bg: "#FBF1F0",
    color: "#EB5757",
  },
  {
    name: "Завершен",
    pluralName: "Завершен",
    encryptedName: "FD",
    pluralNameKk: "Аяқталды",
    bg: "#F2F2F2",
    color: "#4F4F4F",
  },
  {
    name: "Доставлен",
    pluralName: "Доставлен",
    encryptedName: "DD",
    pluralNameKk: "Жеткізілді",
    bg: "#F2F2F2",
    color: "#4F4F4F",
  },
  {
    name: "Добавлено доверенное лицо",
    pluralName: "Добавлено доверенное лицо",
    encryptedName: "PA",
    pluralNameKk: "Сенімді адам қосылды",
    bg: "#F2F2F2",
    color: "#4F4F4F",
  },
];

export const statusProductList = [
  {
    name: "Активно",
    pluralName: "Активно",
    encryptedName: "AC",
    pluralNameKk: "Белсенді",
    color: "#092F33",
    background: "#219653",
  },
  {
    name: "В архиве",
    pluralName: "В архиве",
    pluralNameKk: "Мұрағатта",
    encryptedName: "AR",
    color: "#828282",
    background: "#BDBDBD",
  },
];
