export const statusList = [
  {
    name: "Создан",
    pluralName: "Создан",
    encryptedName: "AD",
    bg: "#EDF4FE",
    color: "#2D9CDB",
  },
  {
    name: "Выставлен счет",
    pluralName: "Выставлен счет",
    encryptedName: "BD",
    bg: "#F6F4FE",
    color: "#9593F2",
  },
  {
    name: "Оплачено",
    pluralName: "Оплачен",
    encryptedName: "PD",
    bg: "#D6EFE6",
    color: "#219653",
  },
  {
    name: "Отменен",
    pluralName: "Отменен",
    encryptedName: "CD",
    bg: "#FBF1F0",
    color: "#EB5757",
  },
  {
    name: "Завершен",
    pluralName: "Завершен",
    encryptedName: "FD",
    bg: "#F2F2F2",
    color: "#4F4F4F",
  },
  {
    name: "Доставлен",
    pluralName: "Доставлен",
    encryptedName: "DD",
    bg: "#F2F2F2",
    color: "#4F4F4F",
  },
  {
    name: "Добавлено доверенное лицо",
    pluralName: "Добавлено доверенное лицо",
    encryptedName: "PA",
    bg: "#F2F2F2",
    color: "#4F4F4F",
  },
];
